---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: community-minecraft
  namespace: community-minecraft
spec:
  template:
    spec:
      $setElementOrder/initContainers:
      initContainers:
      - name: update-plugins
        image: devlaunchers/community-minecraft-plugins:sha-59aa0e7
