RestrictInventoryPut: true
UpdaterChecker: true
Debug: false
PvP: true
PvE: false
BlockPlace: false
BlockPistonPush: true
DisableBlockSpreadEvent: true
DisableBlockGrowEvent: true
DisableStructureGrowEvent: true
Disabled-Items:
- acacia_sapling
- allium
- ancient_debris
- anvil
- apple
- arrow
- barrier
- bat_spawn_egg
- beacon
- bedrock
- bee_nest
- bee_spawn_egg
- beef
- beehive
- beetroot
- beetroot_seeds
- beetroot_soup
- birch_sapling
- black_dye
- black_shulker_box
- blast_furnace
- blaze_powder
- blaze_rod
- blaze_spawn_egg
- blue_dye
- blue_shulker_box
- bone_meal
- book
- bookshelf
- bow
- bowl
- bread
- brewing_stand
- brown_dye
- brown_shulker_box
- cake
- carrot
- carrot_on_a_stick
- cartography_table
- carved_pumpkin
- cat_spawn_egg
- cave_spider_spawn_egg
- chain_command_block
- chainmail_boots
- chainmail_chestplate
- chainmail_helmet
- chainmail_leggings
- chicken_spawn_egg
- clay
- clay_ball
- clock
- coal
- coal_block
- coal_ore
- cocoa_beans
- cod
- cod_bucket
- cod_spawn_egg
- command_block_minecart
- compass
- conduit
- cooked_beef
- cooked_chicken
- cooked_cod
- cooked_mutton
- cooked_porkchop
- cooked_rabbit
- cooked_salmon
- cookie
- cow_spawn_egg
- creeper_spawn_egg
- crimson_button
- crimson_door
- crimson_fence
- crimson_fence_gate
- crimson_fungus
- crimson_hyphae
- crimson_nylium
- crimson_planks
- crimson_pressure_plate
- crimson_roots
- crimson_sign
- crimson_slab
- crimson_stairs
- crimson_stem
- crimson_trapdoor
- crossbow
- crying_obsidian
- cyan_dye
- cyan_shulker_box
- dark_prismarine
- dark_prismarine_slab
- dark_prismarine_stairs
- diamond
- diamond_axe
- diamond_block
- diamond_boots
- diamond_chestplate
- diamond_helmet
- diamond_hoe
- diamond_horse_armor
- diamond_leggings
- diamond_ore
- diamond_pickaxe
- diamond_shovel
- diamond_sword
- dolphin_spawn_egg
- donkey_spawn_egg
- dragon_breath
- dragon_egg
- dragon_head
- dried_kelp
- dried_kelp_block
- drowned_spawn_egg
- egg
- elder_guardian_spawn_egg
- elytra
- emerald
- emerald_block
- emerald_ore
- enchanted_book
- enchanted_golden_apple
- enchanting_table
- end_crystal
- end_portal_frame
- end_rod
- end_stone
- end_stone_brick_slab
- end_stone_brick_stairs
- end_stone_brick_wall
- end_stone_bricks
- ender_chest
- ender_eye
- ender_pearl
- enderman_spawn_egg
- endermite_spawn_egg
- evoker_spawn_egg
- experience_bottle
- feather
- fermented_spider_eye
- fire_charge
- firework_rocket
- firework_star
- fishing_rod
- fletching_table
- flint
- flint_and_steel
- fox_spawn_egg
- furnace
- furnace_minecart
- ghast_spawn_egg
- ghast_tear
- glass_bottle
- glistering_melon_slice
- glowstone
- glowstone_dust
- gold_block
- gold_ingot
- gold_nugget
- gold_ore
- golden_apple
- golden_axe
- golden_boots
- golden_carrot
- golden_chestplate
- golden_helmet
- golden_hoe
- golden_horse_armor
- golden_leggings
- golden_pickaxe
- golden_shovel
- golden_sword
- gray_dye
- gray_shulker_box
- green_dye
- green_shulker_box
- grindstone
- guardian_spawn_egg
- gunpowder
- hay_block
- heart_of_the_sea
- hoglin_spawn_egg
- honey_block
- honey_bottle
- honeycomb
- honeycomb_block
- horse_spawn_egg
- husk_spawn_egg
- infested_chiseled_stone_bricks
- infested_cobblestone
- infested_cracked_stone_bricks
- infested_mossy_stone_bricks
- infested_stone
- infested_stone_bricks
- ink_sac
- iron_axe
- iron_bars
- iron_block
- iron_boots
- iron_chestplate
- iron_door
- iron_helmet
- iron_hoe
- iron_horse_armor
- iron_ingot
- iron_leggings
- iron_nugget
- iron_ore
- iron_pickaxe
- iron_shovel
- iron_sword
- iron_trapdoor
- jukebox
- kelp
- lapis_block
- lapis_lazuli
- lapis_ore
- lava
- lava_bucket
- leather
- leather_boots
- leather_chestplate
- leather_helmet
- leather_horse_armor
- leather_leggings
- light_blue_dye
- light_blue_shulker_box
- light_gray_dye
- light_gray_shulker_box
- lime_dye
- lime_shulker_box
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- lingering_potion
- llama_spawn_egg
- lodestone
- loom
- magenta_dye
- magenta_shulker_box
- magma_block
- magma_cream
- magma_cube_spawn_egg
- map
- melon
- melon_seeds
- melon_slice
- milk_bucket
- minecart
- mooshroom_spawn_egg
- mule_spawn_egg
- mushroom_stew
- music_disc_11
- music_disc_13
- music_disc_blocks
- music_disc_cat
- music_disc_chirp
- music_disc_far
- music_disc_mall
- music_disc_mellohi
- music_disc_pigstep
- music_disc_stal
- music_disc_strad
- music_disc_wait
- music_disc_ward
- mutton
- name_tag
- nautilus_shell
- nether_gold_ore
- nether_star
- nether_wart
- nether_wart_block
- netherite_axe
- netherite_block
- netherite_boots
- netherite_chestplate
- netherite_helmet
- netherite_hoe
- netherite_ingot
- netherite_leggings
- netherite_pickaxe
- netherite_scrap
- netherite_shovel
- netherite_sword
- note_block
- oak_sapling
- ocelot_spawn_egg
- orange_dye
- orange_shulker_box
- panda_spawn_egg
- paper
- parrot_spawn_egg
- phantom_membrane
- phantom_spawn_egg
- pig_spawn_egg
- piglin_brute_spawn_egg
- piglin_spawn_egg
- pillager_spawn_egg
- pink_dye
- pink_shulker_box
- poisonous_potato
- polar_bear_spawn_egg
- popped_chorus_fruit
- porkchop
- potato
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- potion
- prismarine
- prismarine_brick_slab
- prismarine_brick_stairs
- prismarine_bricks
- prismarine_crystals
- prismarine_shard
- prismarine_slab
- prismarine_stairs
- prismarine_wall
- pufferfish
- pufferfish_bucket
- pufferfish_spawn_egg
- pumpkin
- pumpkin_pie
- pumpkin_seeds
- purple_dye
- purple_shulker_box
- purpur_block
- purpur_pillar
- purpur_slab
- purpur_stairs
- quartz
- quartz_block
- quartz_bricks
- quartz_pillar
- quartz_slab
- quartz_stairs
- rabbit
- rabbit_foot
- rabbit_hide
- rabbit_spawn_egg
- rabbit_stew
- ravager_spawn_egg
- red_dye
- red_shulker_box
- repeating_command_block
- respawn_anchor
- rotten_flesh
- saddle
- salmon
- salmon_bucket
- salmon_spawn_egg
- scute
- shears
- sheep_spawn_egg
- shield
- shroomlight
- shulker_box
- shulker_shell
- shulker_spawn_egg
- silverfish_spawn_egg
- skeleton_horse_spawn_egg
- skeleton_skull
- skeleton_spawn_egg
- skull_banner_pattern
- slime_spawn_egg
- smoker
- smooth_quartz
- smooth_quartz_slab
- smooth_quartz_stairs
- snowball
- spawner
- spectral_arrow
- spider_eye
- spider_spawn_egg
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- splash_potion
- spruce_sapling
- squid_spawn_egg
- stick
- stone_axe
- stone_hoe
- stone_pickaxe
- stone_shovel
- stone_sword
- stray_spawn_egg
- strider_spawn_egg
- suspicious_stew
- sweet_berries
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tipped_arrow
- tnt
- tnt_minecart
- totem_of_undying
- trader_llama_spawn_egg
- trident
- tropical_fish
- tropical_fish_bucket
- tropical_fish_spawn_egg
- turtle_egg
- turtle_helmet
- turtle_spawn_egg
- vex_spawn_egg
- villager_spawn_egg
- vindicator_spawn_egg
- wandering_trader_spawn_egg
- warped_button
- warped_door
- warped_fence
- warped_fence_gate
- warped_fungus
- warped_fungus_on_a_stick
- warped_hyphae
- warped_nylium
- warped_planks
- warped_pressure_plate
- warped_roots
- warped_sign
- warped_slab
- warped_stairs
- warped_stem
- warped_trapdoor
- warped_wart_block
- water
- water_bucket
- white_dye
- white_shulker_box
- witch_spawn_egg
- wither_rose
- wither_skeleton_skull
- wither_skeleton_spawn_egg
- wolf_spawn_egg
- wooden_axe
- wooden_hoe
- wooden_pickaxe
- wooden_shovel
- wooden_sword
- writable_book
- written_book
- yellow_dye
- zoglin_spawn_egg
- zombie_head
- zombie_horse_spawn_egg
- zombie_spawn_egg
- zombie_villager_spawn_egg
- zombified_piglin_spawn_egg
username: root
host: localhost
port: 3306
database: restrictcreative
password: password
