armor: true
debug: false
debug_level: ERROR
dont_spam_chat: false
enderchest: true
no_creative_pvp: false
no_drops: false
no_falling_drops: false
no_pickups: false
no_villager_trade: false
no_wither_spawn: false
no_golem_spawn: false
remove_potions: true
restrict_creative: false
containers:
- ANVIL
- BARREL
- BEACON
- BEE_NEST
- BEEHIVE
- BLACK_SHULKER_BOX
- BLAST_FURNACE
- BLUE_SHULKER_BOX
- BREWING_STAND
- BROWN_SHULKER_BOX
- CAMPFIRE
- CARTOGRAPHY_TABLE
- CHEST
- CHIPPED_ANVIL
- COMPOSTER
- CYAN_SHULKER_BOX
- DAMAGED_ANVIL
- DISPENSER
- DROPPER
- ENCHANTING_TABLE
- ENDER_CHEST
- FLETCHING_TABLE
- FURNACE
- GRAY_SHULKER_BOX
- GREEN_SHULKER_BOX
- GRINDSTONE
- HOPPER
- JUKEBOX
- LECTERN
- LIGHT_BLUE_SHULKER_BOX
- LIGHT_GRAY_SHULKER_BOX
- LIME_SHULKER_BOX
- LOOM
- MAGENTA_SHULKER_BOX
- ORANGE_SHULKER_BOX
- PINK_SHULKER_BOX
- PURPLE_SHULKER_BOX
- RED_SHULKER_BOX
- SHULKER_BOX
- SMITHING_TABLE
- SMOKER
- SOUL_CAMPFIRE
- STONECUTTER
- TRAPPED_CHEST
- WHITE_SHULKER_BOX
- YELLOW_SHULKER_BOX
save_on_death: true
survival_on_world_change: false
xp: true
track_creative_place:
  enabled: false
  break_no_drop: false
  no_piston_move: false
  attached_block: false
  no_seeds_from_pumpkin: false
  worlds:
  - world
  dont_track:
  - STONE
  - DIRT
  dont_track_is_whitelist: false
creative_blacklist: false
blacklist:
- TNT
- BEDROCK
- LAVA_BUCKET
- ARMOR_STAND
break_bedrock: false
command_blacklist: false
commands:
- give
- i
- buy
- sell
restrict_spectator: false
bypass:
  inventories: true
  items: true
  blacklist: false
  survival: false
  commands: false
  trades: false
uuid_conversion_done: true
blocks_conversion_done: true
storage:
  mysql:
    server: localhost
    port: 3306
    database: GMI
    user: bukkit
    password: mysecurepassword
    pool_size: 10
    test_connection: false
    useSSL: true
  database: sqlite
  prefix: ''
creative_world:
  location: last_known
  world: creative
  switch_to: false
