---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: community-minecraft
  name: community-minecraft
  labels:
    app: community-minecraft
  annotations:
    fluxcd.io/automated: "true"
    # Update when image tag is sha-*
    fluxcd.io/tag.community-minecraft-plugins: regex:^sha-*
spec:
  replicas: 1
  serviceName: community-minecraft
  selector:
    matchLabels:
      app: community-minecraft
  template:
    metadata:
      labels:
        app: community-minecraft
    spec:
      initContainers:
       # Image has is used to signal new versions
      - name: update-plugins
        image: devlaunchers/community-minecraft-plugins:sha-74c6b81
        command: [ "/bin/bash", "-c", "--" ]
        #Replace plugins dir with latest plugins from the image which is also a git dir
        args: ["cd /minecraft/community-minecraft/community-minecraft-data/server/plugins && git fetch && git reset --hard origin/main"]
        volumeMounts:
        - name: persistent-storage
          mountPath: "/minecraft/community-minecraft/community-minecraft-data"
      containers:
      - name: community-minecraft
        image: devlaunchers/community-minecraft:main
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "cd /minecraft/community-minecraft/community-minecraft-data/server; ./start.sh server.jar" ]
        ports:
        - containerPort: 25565
          protocol: TCP
        - containerPort: 25565
          protocol: UDP
        - containerPort: 22
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 3172Mi
          requests:
            cpu: 750m
            memory: 2048Mi
        livenessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        volumeMounts:
        - name: persistent-storage
          mountPath: "/minecraft/community-minecraft/community-minecraft-data"
      nodeSelector:
        location: togglebox-dev
      volumes:
      - name: persistent-storage
        hostPath:
          path: /mnt/data/community-minecraft
          type: Directory
