# HeadsPlus by Thatsmusic99 - Config wiki: https://github.com/Thatsmusic99/HeadsPlus/wiki/Configuring-config.yml
locale: en_us
smart-locale: false
mysql:
  host: localhost
  port: '3306'
  database: db
  username: username
  password: password
  enabled: false
theme-colours:
  '1': DARK_BLUE
  '2': GOLD
  '3': GRAY
  '4': DARK_AQUA
blacklist:
  world:
    enabled: true
    list: []
  default:
    enabled: true
    list: []
whitelist:
  world:
    enabled: false
    list: []
  default:
    enabled: false
    list: []
plugin:
  larger-menus: false
  autograb:
    enabled: false
    add-as-enabled: true
    section: players
    title: '&8[&6{player}&8]'
    price: default
  mechanics:
    theme: classic
    plugin-theme-dont-change: classic
    update:
      check: true
      notify: true
    allow-looting-enchantment: true
    looting:
      ignored-entities: []
      use-old-system: false
      thresholds:
        common: 100
        uncommon: 20
        rare: 5
    stop-placement-of-sellable-heads: false
    sellhead-gui: true
    debug:
      create-debug-files: true
      print-stacktraces-in-console: true
    anvil-menu-search: false
    mythicmobs:
      no-hp-drops: true
    round-balance-to-2-d-p: true
    boss-bar:
      enabled: true
      color: RED
      title: '&c&lXP to next HP level'
      lifetime: 5
    broadcasts:
      level-up: true
      challenge-complete: true
    leaderboards:
      cache-boards: true
      cache-lifetime-seconds: 300
    xp:
      crafting: 10
      head-drops: 10
      selling: 10
    suppress-gui-warnings: true
    blocked-spawn-causes:
    - SPAWNER_EGG
    use-tellraw: false
    masks:
      check-interval: 60
      reset-after-x-intervals: 20
      effect-length: 12000
    sellhead-ids-case-sensitive: true
  perks:
    ascii-art: true
    sell-heads: true
    drop-heads: true
    craft-heads: false
    disable-crafting: false
    heads-selector: true
    challenges: true
    leaderboards: true
    levels: true
    player-death-messages: false
    death-messages:
    - '&b{player} &3was killed by &b{killer} &3and had their head removed!'
    - '&b{killer} &3finished the job and removed the worst part of &b{player}&3: The
      head.'
    - '&3The server owner screamed at &b{player} &3"OFF WITH HIS HEAD!"&3. &b{killer}
      &3finished the job.'
    smite-player-if-they-get-a-head: false
    mask-powerups: true
    drops:
      ignore-players: []
      needs-killer: false
      entities-requiring-killer:
      - player
    pvp:
      player-balance-competition: false
      use-killer-balance: false
      percentage-lost: 5
      percentage-balance-for-head: 5
    interact:
      middle-click-head: true
      click-head: true
    xp:
      allow-negative: false
